name: Test Suite

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            llvm: 18
          - os: ubuntu-latest
            llvm: 14

    steps:
      - uses: actions/checkout@v4

      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          brew install \
            llvm@${{ matrix.llvm }} \
            libxml2 \
            cpanminus
          echo "export PATH=\"/usr/local/opt/llvm@${{ matrix.llvm }}/bin:$PATH\"" >> $GITHUB_PATH

      - name: Install Ubuntu dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            libomp-dev \
            clang-${{ matrix.llvm }} \
            clang-tools-${{ matrix.llvm }} \
            llvm-${{ matrix.llvm }} \
            libxml2 \
            libxml2-dev \
            zlib1g-dev \
            cpanminus && \
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-${{ matrix.llvm }} 100 && \
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-${{ matrix.llvm }} 100 && \
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/clang-${{ matrix.llvm }} 100 && \
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/clang++-${{ matrix.llvm }} 100

      - name: Cache cpanm
        uses: actions/cache@v4
        with:
          path: ~/.cpanm
          key: "${{ runner.os }}-llvm${{ matrix.llvm }}-cpanm-${{ hashFiles('cpanfile') }}"
  
      - name: Install Perl modules
        shell: bash
        run: |
          if [ "$(uname)" = "Darwin" ]; then
            export PKG_CONFIG_PATH="$(brew --prefix libxml2)/lib/pkgconfig:$PKG_CONFIG_PATH"
          fi
          cpanm --notest --installdeps .

      - name: Run test suite
        run: |
          if [ "$(uname)" = "Darwin" ]; then
            CORES=$(sysctl -n hw.ncpu)
            export WITH_OPENMP=0
          else
            CORES=$(nproc)
          fi
      
          VERBOSE=1 WITH_COVERAGE=0 make test -j"$CORES"
          
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() 
        with:
          report_paths: 'build/tests/.test/report.xml'
     
      